# Generated by Django 4.1.3 on 2022-11-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='matricula',
            field=models.CharField(max_length=8, verbose_name='Matricula'),
        ),
    ]
