# Generated by Django 4.1.3 on 2022-11-23 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDePublicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Publicacion',
                'verbose_name_plural': 'Tipos de Publicacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellido_paterno', models.CharField(max_length=255, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=255, null=True, verbose_name='Apellido materno')),
                ('matricula', models.CharField(max_length=255, unique=True, verbose_name='Matricula')),
                ('asesor_interno', models.CharField(max_length=255, verbose_name='Asesor interno')),
                ('asesor_externo', models.CharField(max_length=255, verbose_name='Asesor externo')),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='archivos.campus')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.carrera')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('materia', models.CharField(max_length=255, verbose_name='Materia')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('pdf', models.FileField(default='', upload_to='archivos/', verbose_name='pdf')),
                ('resumen', models.TextField(blank=True, default='', verbose_name='Resumen')),
                ('autor', models.ManyToManyField(to='archivos.autor')),
                ('tipo_de_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.tipodepublicacion')),
            ],
        ),
    ]
