# Generated by Django 4.1.3 on 2022-11-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='imagen',
            field=models.ImageField(upload_to='imgs/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='pdf',
            field=models.FileField(default='', upload_to='pdfs/', verbose_name='pdf'),
        ),
    ]
