# Generated by Django 4.1.3 on 2022-11-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_alter_archivo_imagen_alter_archivo_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='autor',
        ),
    ]
