# Generated by Django 4.1.3 on 2022-11-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_remove_archivo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='autor',
            field=models.ManyToManyField(to='archivos.autor'),
        ),
    ]
